"""Initial migration.

Revision ID: d7e3034e530c
Revises: 
Create Date: 2021-11-09 15:45:06.474074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e3034e530c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itemtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('office',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('equipment', sa.Column('identifier', sa.String(length=200), nullable=True))
    op.add_column('equipment', sa.Column('item_type', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('main_option', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('use_type', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('office', sa.Integer(), nullable=True))
    op.add_column('equipment', sa.Column('document', sa.String(length=200), nullable=True))
    op.add_column('equipment', sa.Column('purchase_date', sa.DateTime(), nullable=True))
    op.add_column('equipment', sa.Column('comment', sa.String(length=500), nullable=True))
    op.add_column('equipment', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'equipment', 'office', ['office'], ['id'])
    op.create_foreign_key(None, 'equipment', 'usetype', ['use_type'], ['id'])
    op.create_foreign_key(None, 'equipment', 'option', ['main_option'], ['id'])
    op.create_foreign_key(None, 'equipment', 'itemtype', ['item_type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_column('equipment', 'created_date')
    op.drop_column('equipment', 'comment')
    op.drop_column('equipment', 'purchase_date')
    op.drop_column('equipment', 'document')
    op.drop_column('equipment', 'office')
    op.drop_column('equipment', 'use_type')
    op.drop_column('equipment', 'main_option')
    op.drop_column('equipment', 'item_type')
    op.drop_column('equipment', 'identifier')
    op.drop_table('usetype')
    op.drop_table('option')
    op.drop_table('office')
    op.drop_table('itemtype')
    # ### end Alembic commands ###
